export const GET_COLORS_REQUEST = "GET_COLORS_REQUEST";
export const GET_COLORS_RESPONSE = "GET_COLORS_RESPONSE";
export const GET_COLORS_ERROR = "GET_COLORS_ERROR";
export const GENERATE_PATTERN_REQUEST = "GENERATE_PATTERN_REQUEST";
export const GENERATE_PATTERN_RESPONSE = "GENERATE_PATTERN_RESPONSE";
export const GENERATE_PATTERN_ERROR = "GENERATE_PATTERN_ERROR";
